apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-nodeport-affinity
spec:
  sessionAffinity: ClientIP
  ports:
    - name: web-port
      port: 80
      targetPort: 80
  selector:
    app: webserver
  type: NodePort
